services:
  coursefinder:
    image: registry.sccs.swarthmore.edu/cs77-s25/coursefinder/coursefinder:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    #environment:
    #env_file:
    #  - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.coursefinder.entrypoints=https"
        - "traefik.http.routers.coursefinder.rule=Host(`coursefinder.sccs.swarthmore.edu`)"
        - "traefik.http.routers.coursefinder.tls=true"
        - "traefik.http.routers.coursefinder.tls.certresolver=letsEncrypt"
        - "traefik.http.services.coursefinder.loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
