services:
  :
    image: registry.sccs.swarthmore.edu/cs77-s25//:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    #env_file:
    #  - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers..entrypoints=https"
        - "traefik.http.routers..rule=Host(`.sccs.swarthmore.edu`)"
        - "traefik.http.routers..tls=true"
        - "traefik.http.routers..tls.certresolver=letsEncrypt"
        - "traefik.http.services..loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
